<a href="https://colab.research.google.com/github/soodeep5/-ds-lab-3/blob/master/IntroductionMachineLled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What we wii cover?
- Creating Single dimensional arrays
- Multidimensional arrays
- Randomly generated arrays
- Element wise operations
- Summarizing operations

### Single dimensional arrays

In [2]:
import numpy as np
#create an array with all the elements to be zeros

np.zeros (5)


array([0., 0., 0., 0., 0.])

In [4]:
#create an array with all the elements to be ones
np.ones (5)

array([1., 1., 1., 1., 1.])

In [6]:
#create an elements of size with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multidimensional arrays

In [23]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.array([[1, 2 ,3 ],
 [4, 5, 6],
         [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a[2]=[1, 1, 1 ]
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [45]:
a[:, 2] = [2, 2, 2]
a

array([[1, 2, 2],
       [4, 5, 2],
       [1, 1, 2]])

In [49]:
np.full([3, 3],10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly generated arrays
- NumPy can create arrays filled with random numbers
- To ensure the reproduciblity, you can set a seed using np.random.seed().
-if you remove or change the seed values, the sequence of random numbers will be changed.

In [53]:
np.random.rand(5)

array([0.13475711, 0.46125246, 0.66260794, 0.5978207 , 0.39199342])

In [55]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [57]:
np.random.randn(5, 2)

array([[ 1.17223107, -0.48103231],
       [-1.00073842, -1.18248113],
       [-0.43654296, -2.64063134],
       [ 0.01571955,  0.02997534],
       [ 0.06243148,  0.37666721]])

In [58]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[17, 54],
       [16, 41],
       [20, 31],
       [24, 67],
       [ 8, 91]])